CREATE TYPE TradeInput AS TABLE(
	ID_TRADE NVARCHAR(36) NOT NULL,
	VALUE DECIMAL(18,2) NOT NULL,
	CLIENT_SECTOR NVARCHAR(20) NOT NULL
)
GO
CREATE TYPE TradeCategoryOutput AS TABLE(
	ID_TRADE_CATEGORY NVARCHAR(36) NOT NULL,
	ID_TRADE NVARCHAR(36) NOT NULL,
	CATEGORY_NAME NVARCHAR(20) NOT NULL
)
GO
CREATE TABLE TRADE (
	ID_TRADE NVARCHAR(36) PRIMARY KEY,
	VALUE DECIMAL(18,2) NOT NULL,
	CLIENT_SECTOR NVARCHAR(20) NOT NULL,
	RISK_CATEGORY NVARCHAR(20) NOT NULL
)
GO